
///////////////////////////////
// Generated by aliens_tables.py
// Don't hand-edit!
///////////////////////////////

package com.medphone.aliens;

import com.medphone.Process;

class AliensTables {
	static final Object[] codes = {
		"DebugProcess", new Boolean(true), new Integer(1), 
		"Cross", new Boolean(true), new Integer(27677), 
		"Safe", new Boolean(true), new Integer(7233), 
		"Resp", new Boolean(true), new Integer(7377), 
		"SampleProcess", new Boolean(false), new Integer(223456), new Integer(654321), 
		"Surfactant", new Boolean(false), new Integer(42), new Integer(43), new Integer(44), new Integer(45), 
		"Antialvin", new Boolean(false), new Integer(333), new Integer(334), new Integer(335), 
		"Travian", new Boolean(false), new Integer(999), new Integer(998), new Integer(997), new Integer(996), new Integer(995), new Integer(994), new Integer(993), new Integer(992), new Integer(991), new Integer(990), 
	};
	
	static Process create_process(String name) {
		if (name.equals("DebugProcess"))
			return new DebugProcess();
		if (name.equals("Cross"))
			return new Cross();
		if (name.equals("Safe"))
			return new Safe();
		if (name.equals("Resp"))
			return new Resp();
		if (name.equals("SampleProcess"))
			return new SampleProcess();
		if (name.equals("Surfactant"))
			return new Surfactant();
		if (name.equals("Antialvin"))
			return new Antialvin();
		if (name.equals("Travian"))
			return new Travian();
		return null;
	}
}

