from codes import reusable, unique, get_code_path
from prefix import PrefixSet

def phoneword(s):
    t = 'abc,def,ghi,jkl,mno,pqrs,tuv,wxyz'.split(',')
    result = ''
    for c in s:
        for i, key in enumerate(t, 2):
            if c in key:
                result += str(i)
                break
        else:
            result += c
    return result
        
codes_dir = 'codes/'

result = []
used = PrefixSet()
for name in reusable+unique:
    print name
    result.append('\t\t"{}", new Boolean({}), '.format(name, str(name in reusable).lower()))


    codes = open(get_code_path(name)).readlines()
    for code in codes:
        code = code.strip()
        code = phoneword(code)

        assert not code.startswith('0'), code
        assert used.can_add(code), code
        used.add(code)

        result.append('new Integer({}), '.format(code))
    result.append('\n')

print len(used), 'codes total'

cases = []
for name in reusable+unique:
    cases.append(
       '\t\tif (name.equals("{0}"))\n'
	   '\t\t\treturn new {0}();\n'.format(name))


template = """
///////////////////////////////
// Generated by aliens_tables.py
// Don't hand-edit!
///////////////////////////////

package com.medphone.aliens;

import com.medphone.Process;

public class AliensTables {
	static final Object[] codes = {
%s	};
	
	public static Process createProcess(String name) {
%s		return null;
	}
}
"""

with open('src/com/medphone/aliens/AliensTables.java', 'w') as fout:
    print>>fout, template%(''.join(result), ''.join(cases))