from codes import reusable, unique

def phoneword(s):
    t = 'abc,def,ghi,jkl,mno,pqrs,tuv,wxyz'.split(',')
    result = ''
    for c in s:
        for i, key in enumerate(t, 2):
            if c in key:
                result += str(i)
                break
        else:
            result += c
    return result
        
codes_dir = 'codes/'

result = []
used_codes = set()
used_prefixes = set()
for name in reusable+unique:
    print name
    result.append('\t\t"{}", new Boolean({}), '.format(name, str(name in reusable).lower()))

    file_name = name
    if name in reusable:
        file_name = 'reusable/'+file_name
    #file_name = 'codes/'+file_name
    file_name = '../../Cards/codes/'+file_name
    if file_name.endswith('Demo'):
        file_name = file_name[:-4]

    codes = open(file_name).readlines()
    for code in codes:
        code = code.strip()
        code = phoneword(code)

        assert not code.startswith('0'), code
        assert code not in used_prefixes, code
        for i in range(1, len(code)+1):
            assert code[:i] not in used_codes, code[:i]+'...'
            used_prefixes.add(code[:i])
        used_codes.add(code)

        result.append('new Integer({}), '.format(code))
    result.append('\n')


cases = []
for name in reusable+unique:
    cases.append(
       '\t\tif (name.equals("{0}"))\n'
	   '\t\t\treturn new {0}();\n'.format(name))


template = """
///////////////////////////////
// Generated by aliens_tables.py
// Don't hand-edit!
///////////////////////////////

package com.medphone.aliens;

import com.medphone.Process;

public class AliensTables {
	static final Object[] codes = {
%s	};
	
	public static Process createProcess(String name) {
%s		return null;
	}
}
"""

with open('src/com/medphone/aliens/AliensTables.java', 'w') as fout:
    print>>fout, template%(''.join(result), ''.join(cases))